version: '2'
services:
  web:
    build: .
    ports:
      - "80:80"
    links:
      - db 
  db:
    build: ./DB/
    restart: always
    volumes:
      - ./localDB:/var/lib/postgresql
    ports:
      - "5432:5432"
