version: '2'
services:
  web:
    build: .
    ports:
      - "80:80"
    links:
      - db 
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - ./localDB:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: pgdb
