version: '2'
services:
  web:
    build: .
    ports:
      - "80:80"
    links:
      - db 
  db:
    build: ./DB/
    restart: always
    volumes:
      - ./localDB:/var/lib/postgresql
  
  environment:
        POSTGRES_USER: pguser
        POSTGRES_PASSWORD: pguser
        POSTGRES_DB: pgdb
