version: '2.1'
services:
  web:
    build: .
    ports:
      - "80:80"
    links:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 10s
      retries: 2
    restart: always
  db:
    build: ./DB/
    restart: always
    volumes:
      - ./localDB:/var/lib/postgresql
  
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: pgdb
